#Chats
SELECT DISTINCT ?item ?itemLabel WHERE {
  ?item wdt:P31 wd:Q146 . # Ce doit être un chat
  ?item rdfs:label ?label . # instead of SERVICE wikibase:label
  FILTER (lang(?label) = "en" || lang(?label) = "mul" || lang(?label) = "fr").
  BIND (str(?label) AS ?itemLabel)
}
