PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

# This query comes from the Wikidata's official examples,
# and actually times out… Of course, there are a lot
# of stars. It took 1000s for us.
SELECT ?star ?images ?apparent_magnitude WHERE {
  ?star wdt:P31 wd:Q523; # is a star!
        wdt:P1215 ?apparent_magnitude;
        wdt:P18 ?images .
  FILTER(?apparent_magnitude < 1)
}
ORDER BY DESC (?apparent_magnitude)
LIMIT 10
